from typing import Any


class AIAnalyzer:
    """
    Provider-independent AI analysis interface.
    """

    def analyze(self, finding: dict[str, Any]) -> dict[str, str]:
        return {
            "explanation": "AI analysis is not configured yet.",
            "impact": "Impact analysis will be generated by the AI provider.",
            "risk_analysis": "Risk analysis is not available yet.",
            "remediation": "AI-generated remediation will be available after provider integration."
        }
